### ISSUE TITLE
Reacquire reprocessed 2015 scenes

### ISSUE THREAD

**Issue by jedsundwall** [landsat-pds/landsat_ingestor#16]
Can we reacquire and replace the 53,206 scenes listed at http://landsat-pds.s3.amazonaws.com/L8.reprocessed.2015.txt?

**Comment by warmerdam** [comment]
We will need to work through how to accomplish this without just causing a big backlog since we are barely keeping up with USGS currently.  Amit will be primarily responsible.

**Comment by kapadia** [comment]
We have a note out to USGS asking for more bandwidth. Waiting to hear from them.

**Comment by kapadia** [comment]
Documenting this here for future use. If we'd like to get a list of modified Landsat scenes for a specific date range, we can do something like:

``` shell
usgs search --node EE LANDSAT_8 --start-date 2015-05-24 --end-date 2015-05-25 --geojson | \
  jq '[ .features[] | { entityId: .properties.entityId, acquisitionDate: .properties.acquisitionDate , modifiedDate: .properties.modifiedDate } ]' | \
    jq '[ .[] | select((.modifiedDate | fromdate) - (.acquisitionDate | fromdate) > 86400) ]'
```

This compares the acquisition date to the modified date, both available fields in the landsat metadata. Scenes with a time difference greater than 1 day are selected.

**Comment by jedsundwall** [comment]
@kapadia ooh. Very cool. It'd probably be worth running that search once a month or so to get any corrected scenes. That is, assuming we can get more bandwidth.

**Comment by kapadia** [comment]
Complete. These scenes are now available on `s3://landsat-pds/`
