### ISSUE TITLE
Scene list is missing ProductId

### ISSUE THREAD

**Issue by Brett55** [landsat-pds/landsat_ingestor#24]
If I download the scene list from `https://landsat-pds.s3.amazonaws.com/c1/L8/scene_list.gz` it contains `productId` as a column name. 

If I download the scene list from `s3://landsat-pds/scene_list.gz` it does NOT contain `productId` as a column name.

Which scene list is considering best?

**Comment by jflasher** [comment]
Hi @Brett55, the first link you point to is for Collection 1 data (https://landsat.usgs.gov/landsat-collections) which moved to using a product ID. The second link is for Pre-Collection data, which uses the scene name. The Collection 1 data is being continuously updated on AWS but if you want access to older data, you'll need to use the Pre-Collection data currently.

**Comment by Brett55** [comment]
@jflasher thanks! this clears it up for me!
