### ISSUE TITLE
Receiving old scenes on SNS topic

### ISSUE THREAD

**Issue by tomtaylor** [landsat-pds/landsat_ingestor#25]
I’ve just subscribed to the Landsat PDS AWS SNS feed, but it looks like I’m getting lots of old scenes through. In the last 12hrs I’ve received hundreds of events, but the most recent acquisition date is 2017-01-12.

Can anyone confirm whether this is expected behaviour? Are new scenes coming through the SNS feed at the moment?

**Comment by matthewhanson** [comment]
I noticed this too over the last week, but it looks like it's all pre-collection data getting updated to collection-1.

**Comment by kapadia** [comment]
Hi all - yes, we have ingested Collection 1 T1 data over the last week to
bring the archive to a more complete form. The pre-collection data will
remain. I hope this updated data is useful for others.

**Comment by tomtaylor** [comment]
Ah OK, that makes sense. Will we see recent acquisitions alongside those as they come in, or will those be delayed until it catches up?

**Comment by kapadia** [comment]
Recent acquisitions are still coming in, and being processed alongside the
archive. No delay in them.

**Comment by jflasher** [comment]
Thanks Amit!

**Comment by tomtaylor** [comment]
@kapadia thanks!
