### ISSUE TITLE
reprocess scenes without .ovr and tiling

### ISSUE THREAD

**Issue by warmerdam** [landsat-pds/landsat_ingestor#5]
Circa March 1st (in 91e9f509203041b32c681d6c55dec326c18642ae) we set things up to tile and build overviews for ingested scenes; however, we still haven't gone back and reprocessed existing scenes. 

There is now an ingestor/for_each_scene.py that can iterate over scenes, and a reprocess_scene.py that can fix up scenes.  Work out a technique to run this for the existing outdated scenes but not newer scenes.

**Comment by kapadia** [comment]
done.
